name: CI/CD Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install backend dependencies
        run: npm install
        working-directory: ./revibe-backend

      - name: Run backend tests
        run: npm test
        working-directory: ./revibe-backend

      - name: Install frontend dependencies
        run: npm install
        working-directory: ./revibe-frontend

      - name: Run frontend tests
        run: npm test
        working-directory: ./revibe-frontend
